<?php

return [
  'route_fortune' => [
    'prefix' => 'fortune',
    'as' => 'fortune.',
    'middleware' => ['web'],
  ],
  'route_fortune_admin' => [
    'prefix' => 'fortune/admin',
    'as' => 'fortune.admin.',
    'middleware' => ['web', 'admin'],
  ],
  'component' => ['admin' => ['layout' => 'pondol-fortune::admin', 'lnb' => 'pondol-fortune::partials.admin-lnb']],
  /**
     * 60갑자 일주(日柱)별 별칭 및 유형 데이터.
     * 'nickname'은 천간의 색상과 지지의 동물을 조합한 상징적인 별칭입니다.
     * 'archetype'은 해당 일주의 성향을 나타내는 대표적인 페르소나/유형입니다.
     */
    'ilju_archetypes' => [
        '甲子' => ['nickname' => '푸른 쥐', 'archetype' => '지혜로운 개척가'],
        '乙丑' => ['nickname' => '푸른 소', 'archetype' => '성실한 현실주의자'],
        '丙寅' => ['nickname' => '붉은 호랑이', 'archetype' => '열정적인 선구자'],
        '丁卯' => ['nickname' => '붉은 토끼', 'archetype' => '따뜻한 예술가'],
        '戊辰' => ['nickname' => '황금 용', 'archetype' => '믿음직한 중재자'],
        '己巳' => ['nickname' => '황금 뱀', 'archetype' => '내실 있는 전략가'],
        '庚午' => ['nickname' => '하얀 말', 'archetype' => '정의로운 개혁가'],
        '辛未' => ['nickname' => '하얀 양', 'archetype' => '우아한 장인'],
        '壬申' => ['nickname' => '검은 원숭이', 'archetype' => '다재다능한 협상가'],
        '癸酉' => ['nickname' => '검은 닭', 'archetype' => '날카로운 비평가'],
        '甲戌' => ['nickname' => '푸른 개', 'archetype' => '책임감 있는 낙천가'],
        '乙亥' => ['nickname' => '푸른 돼지', 'archetype' => '친절한 이상주의자'],
        '丙子' => ['nickname' => '붉은 쥐', 'archetype' => '솔직한 양심가'],
        '丁丑' => ['nickname' => '붉은 소', 'archetype' => '지혜로운 봉사자'],
        '戊寅' => ['nickname' => '황금 호랑이', 'archetype' => '신뢰의 리더'],
        '己卯' => ['nickname' => '황금 토끼', 'archetype' => '온화한 원칙주의자'],
        '庚辰' => ['nickname' => '하얀 용', 'archetype' => '의리를 지키는 리더'],
        '辛巳' => ['nickname' => '하얀 뱀', 'archetype' => '세련된 재능가'],
        '壬午' => ['nickname' => '검은 말', 'archetype' => '자유로운 지략가'],
        '癸未' => ['nickname' => '검은 양', 'archetype' => '신중한 현실주의자'],
        '甲申' => ['nickname' => '푸른 원숭이', 'archetype' => '고독한 의리파'],
        '乙酉' => ['nickname' => '푸른 닭', 'archetype' => '진취적인 실용주의자'],
        '丙戌' => ['nickname' => '붉은 개', 'archetype' => '명랑한 중재자'],
        '丁亥' => ['nickname' => '붉은 돼지', 'archetype' => '논리적인 예술가'],
        '戊子' => ['nickname' => '황금 쥐', 'archetype' => '치밀한 완벽주의자'],
        '己丑' => ['nickname' => '황금 소', 'archetype' => '묵묵한 관리자'],
        '庚寅' => ['nickname' => '하얀 호랑이', 'archetype' => '카리스마 있는 팔방미인'],
        '辛卯' => ['nickname' => '하얀 토끼', 'archetype' => '감성적인 리더'],
        '壬辰' => ['nickname' => '검은 용', 'archetype' => '화통한 전략가'],
        '癸巳' => ['nickname' => '검은 뱀', 'archetype' => '지혜로운 활동가'],
        '甲午' => ['nickname' => '푸른 말', 'archetype' => '순수한 도전자'],
        '乙未' => ['nickname' => '푸른 양', 'archetype' => '합리적인 예술가'],
        '丙申' => ['nickname' => '붉은 원숭이', 'archetype' => '낙천적인 재능가'],
        '丁酉' => ['nickname' => '붉은 닭', 'archetype' => '감성적인 원칙주의자'],
        '戊戌' => ['nickname' => '황금 개', 'archetype' => '성실한 신념가'],
        '己亥' => ['nickname' => '황금 돼지', 'archetype' => '논리적인 실속파'],
        '庚子' => ['nickname' => '하얀 쥐', 'archetype' => '고독한 혁신가'],
        '辛丑' => ['nickname' => '하얀 소', 'archetype' => '뚝심 있는 장인'],
        '壬寅' => ['nickname' => '검은 호랑이', 'archetype' => '유연한 포용가'],
        '癸卯' => ['nickname' => '검은 토끼', 'archetype' => '총명한 참모'],
        '甲辰' => ['nickname' => '푸른 용', 'archetype' => '진취적인 리더'],
        '乙巳' => ['nickname' => '푸른 뱀', 'archetype' => '상상력이 풍부한 강직가'],
        '丙午' => ['nickname' => '붉은 말', 'archetype' => '화려한 이상주의자'],
        '丁未' => ['nickname' => '붉은 양', 'archetype' => '정열적인 실천가'],
        '戊申' => ['nickname' => '황금 원숭이', 'archetype' => '고독한 신용가'],
        '己酉' => ['nickname' => '황금 닭', 'archetype' => '재치 있는 생활인'],
        '庚戌' => ['nickname' => '하얀 개', 'archetype' => '따뜻한 카리스마'],
        '辛亥' => ['nickname' => '하얀 돼지', 'archetype' => '지혜로운 탐구자'],
        '壬子' => ['nickname' => '검은 쥐', 'archetype' => '강인한 개척가'],
        '癸丑' => ['nickname' => '검은 소', 'archetype' => '명랑한 전략가'],
        '甲寅' => ['nickname' => '푸른 호랑이', 'archetype' => '순수한 정의파'],
        '乙卯' => ['nickname' => '푸른 토끼', 'archetype' => '부드러운 실천가'],
        '丙辰' => ['nickname' => '붉은 용', 'archetype' => '적극적인 중재자'],
        '丁巳' => ['nickname' => '붉은 뱀', 'archetype' => '순수한 승부사'],
        '戊午' => ['nickname' => '황금 말', 'archetype' => '뚝심 있는 노력가'],
        '己未' => ['nickname' => '황금 양', 'archetype' => '온화한 봉사자'],
        '庚申' => ['nickname' => '하얀 원숭이', 'archetype' => '자신감 넘치는 능력가'],
        '辛酉' => ['nickname' => '하얀 닭', 'archetype' => '고독한 완벽주의자'],
        '壬戌' => ['nickname' => '검은 개', 'archetype' => '호탕한 지식인'],
        '癸亥' => ['nickname' => '검은 돼지', 'archetype' => '자유로운 평화주의자'],
    ],
];
